name: biohub_rnaseq
channels:
 - bioconda
 - conda-forge
 - r
 - defaults
dependencies:
  - snakemake
  - r-base
  - conda-forge::parallel
  - conda-forge::pigz
  - bioconda::sra-tools
  - fastp
  - bioconda::multiqc
  - bioconda::samtools
  - bioconda::star
  - bioconda::rsem
  - bioconda::gatk4
