name: biohub_rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.4.2
  - conda-forge::r-tidyverse
  - bioconda::bioconductor-biocinstaller
  - bioconda::bioconductor-deseq2
  d- bioconda::bioconductor-org.Hs.eg.db
  - bioconda::bioconductor-reactomepa 
  # - bioconda::bioconductor-Rsamtools
  # - bioconda::bioconductor-txdbmaker
  # - bioconda::bioconductor-GenomicFeatures
  # - bioconda::bioconductor-GenomicAlignments
  # - bioconda::bioconductor-BiocParallel 
  - conda-forge::pigz
  - python=3.11
  - snakemake
  - multiqc
  - fastp
  - bioconda::sra-tools
  - bioconda::samtools
  - bioconda::star
  - bioconda::rsem