name: biohub_rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.4.2
  - conda-forge::r-tidyverse
  - bioconda::bioconductor-biocinstaller
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-reactomepa 
  - conda-forge::pigz
  - python=3.11
  - snakemake
  - multiqc
  - fastp
  - bioconda::sra-tools
  - bioconda::samtools
  - bioconda::star
  - bioconda::rsem